### ISSUE TITLE
Scaled OS bug

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#100]
- 1st call of dialog: checkboxs are ok (2 checks)
- 2nd call of dialog: check "File" bad (screen was before)
and
```
Loading session: history session.json
Startup: total: 790ms, including plugins: 15ms
Python 3.5.4
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\cudatext\py\cudatext.py", line 888, in _dlg_proc_callback_proxy
    return _live[info](id_dlg, id_ctl, data=data)
  File "C:\cudatext\py\cuda_options_editor\cd_plug_lib.py", line 1625, in da_c_callbk
    upds    = u_callbk(cid, self, data)
  File "C:\cudatext\py\cuda_options_editor\cd_opts_dlg.py", line 1319, in do_menu
    live_fltr=m.stores[m.subset+'live_fltr']
KeyError: 'df.live_fltr'
 
 
```

**Comment by Alexey-T** [comment]
может креш от нажатия = ? не уверен.

**Comment by kvichans** [comment]
2. пофиксил
