### ISSUE TITLE
Err on filter "fold"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#41]
Ввожу тут фильтр fold, [enter] --

Python 3.5.2
Loading icons: LibreOffice_24x24
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 45, in dlg_cuda_opts
    , subset='def.'
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 393, in dlg_opt_editor
    aid, vals, fid, chds = dlg_wrapper(f('{} ({})', title, VERSION_V), DLG_W, DLG_H, cnts, vals, focus_cid=fid)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_plug_lib.py", line 383, in dlg_wrapper
    raise Exception(f('No cid(s) for tid(s): {}', no_tids))
Exception: No cid(s) for tid(s): {'kved'}

**Comment by Alexey-T** [comment]
![fold](https://cloud.githubusercontent.com/assets/4154978/24818149/570220dc-1bf0-11e7-8b0e-49b167c83651.png)

**Comment by kvichans** [comment]
Повторил

**Comment by kvichans** [comment]
fixed 1.1.9
