### ISSUE TITLE
err on change LineNumbers 

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#45]
numbers_style меняю- с дефолта - на each_10th.
(Это 2-й ПК)

```
[ 0.03"]parse_raw_keys_info:648 Bad comment at key minimap_char_width
[ 0.05"]parse_raw_keys_info:648 Bad comment at key key_page_size
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/cuda/cuda/app/py/cuda_options_editor/cd_opts_dlg.py", line 44, in dlg_cuda_opts
    , subset='def.'
  File "/home/user/cuda/cuda/app/py/cuda_options_editor/cd_opts_dlg.py", line 499, in dlg_opt_editor
    val_l   = font_l    if frm_sel=='font' else     list(var_sel.keys())
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by Alexey-T** [comment]
Cudatxt 1.7.0.3, тут.

**Comment by Alexey-T** [comment]
Повторил на 2х ПК
