### ISSUE TITLE
Er on entering filter "theme"

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#51]
Ввод фильтра "theme"[enter]
```
Python 3.5.2
Loading icons: LibreOffice_24x24
[ 0.02"]parse_cmnt:1524 No folder "data/codetreeicons" from
Tree: Icons theme
Folders from: data/codetreeicons
[ 0.05"]parse_cmnt:1524 No folder "data/sideicons" from
Sidebar icons theme
Folders from: data/sideicons
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 47, in dlg_cuda_opts
    , subset='def.'
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 57, in dlg_opt_editor
    dlg_opt_editor_wr(title, keys_info, path_raw_keys_info, path_svd_keys_info, subset)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 319, in dlg_opt_editor_wr
    aid, vals, fid, chds = dlg_wrapper(f('{} ({})', title, VERSION_V), DLG_W, DLG_H, cnts, vals, focus_cid=fid)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_plug_lib.py", line 467, in dlg_wrapper
    items   = '\t'.join(items)
TypeError: can only join an iterable
```

**Comment by Alexey-T** [comment]
Cud release 1.8.5

**Comment by kvichans** [comment]
У меня нет повторения.
Поэтому правка наугад.
Помогло?

**Comment by Alexey-T** [comment]
помогло.
