### ISSUE TITLE
Er on change caret_shape to 2pixels

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#62]
```
Python 3.4.3
[ 0.01"]parse_raw_keys_info:698 Too few variants (1) for key ui_tree_theme
Change in user.json: "caret_shape": 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 47, in dlg_cuda_opts
    , subset='def.'
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 57, in dlg_opt_editor
    dlg_opt_editor_wr(title, keys_info, path_raw_keys_info, path_svd_keys_info, subset)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 421, in dlg_opt_editor_wr
    new_val = vals['eded']
KeyError: 'eded'
```

**Comment by kvichans** [comment]
Не повторил

**Comment by Alexey-T** [comment]
fixed.
