### ISSUE TITLE
V2, crash on show

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#75]
```
Startup: total: 690ms, including plugins: 14ms
Python 3.5.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 1648, in dlg_cuda_options
    ).show(_('CudaText options'))
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 727, in show
    ,   ctrls=m.get_cnts()
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 848, in get_cnts
    m.itms  = get_tbl_data(m.opts_full, m.cond_s, m.ops_only, m.sort, m.col_ws)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 835, in get_tbl_data
    cols    = get_tbl_cols(opts_full, SKWULFs, sort, col_ws)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 794, in get_tbl_cols
    ,d(nm=sort_cs[6]+M.COL_NMS[6], wd=col_ws[6] ,mi=M.COL_MWS[6])
IndexError: list index out of range
```

**Comment by kvichans** [comment]
Что изменилось?

**Comment by kvichans** [comment]
Удалите settings\cuda_options_editor.json

**Comment by Alexey-T** [comment]
можно читать конфиг и не падать?

**Comment by kvichans** [comment]
Я пока не понял причины. "Удалить", чтобы отсечь гипотезу

**Comment by kvichans** [comment]
Как повторить? (Если оно повторяется)

**Comment by Alexey-T** [comment]
Надо было сохранить конфиг, никак
