### ISSUE TITLE
crash on start#2

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#79]
```
Startup: total: 410ms, including plugins: 22ms
Python 3.6.3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 1633, in dlg_cuda_options
    ).show(_('CudaText options'))
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 722, in show
    ,   ctrls=m.get_cnts()
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 845, in get_cnts
    m.itms  = get_tbl_data(m.opts_full, m.cond_s, m.ops_only, m.sort, m.col_ws)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 832, in get_tbl_data
    cols    = get_tbl_cols(opts_full, SKWULFs, sort, col_ws)
  File "/home/user/.cudatext/py/cuda_options_editor/cd_opts_dlg.py", line 791, in get_tbl_cols
    ,d(nm=sort_cs[6]+cnms[6], wd=col_ws[6] ,mi=M.COL_MWS[6])
IndexError: list index out of range
```

**Comment by Alexey-T** [comment]
Zip config 
[cuda_options_editor.zip](https://github.com/kvichans/cuda_options_editor/files/1957401/cuda_options_editor.zip)

**Comment by kvichans** [comment]
Что делали? Удаляли json перед запуском ОпРед?

**Comment by Alexey-T** [comment]
Обновил плаг , вызывал старый диалог версии один

**Comment by Alexey-T** [comment]
проверьте с моим конфигом плиз

**Comment by kvichans** [comment]
Теперь работает с вашим конфигом
